apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- lidarr-deploy.yaml
- lidarr-pvc.yaml
- lidarr-svc.yaml
- lidarr-ing.yaml
images:
- name: linuxserver/lidarr
  newTag: 8.1.2135
labels:
- includeSelectors: true
  pairs:
    app: lidarr
