---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetection
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetection
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: changedetection
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: changedetection
        image: dgtlmoon/changedetection.io
        imagePullPolicy: Always
        # MountVolume.SetUp failed for volume "kube-api-access ca.crt no space left
        # resources:
        #   limits:
        #     memory: 300
        #   requests:
        #     memory: 150
        volumeMounts:
        - mountPath: /datastore
          name: datastore
      restartPolicy: Always
      volumes:
      - name: datastore
        persistentVolumeClaim:
          claimName: changedetection
status: {}
