apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openfaas-functions
  namespace: openfaas
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app/openfaas/functions
    repoURL: https://github.com/radamhu/argocd
  syncPolicy:
    automated:
      selfHeal: true
