image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

serviceAccount:
  annotations: {}

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

health:
  enabled: true
  port: main
  type: HTTP
  path: /

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

terminationGracePeriodSeconds: 30

args: []
command: []

envs: []

secretEnvs: []

configMaps: []
# - name: ""
#   mountPath: ""
#   subPath: ""
#   content: ""

hostPaths: []
# - name: ""
#   hostPath: ""
#   containerPath: ""
#   readOnly: false
#   type: "DirectoryOrCreate"

envsubst:
  image:
    repository: nixery.dev/shell/envsubst
    tag: "latest@sha256:04e9a26389dbd1a762e50d53c36b09ecf3bfbf0117f400486b6ee5064a3e0e63"
  files: []
  # - src:
  #   dest:

concurrencyPolicy: Forbid
parallelism: 1
schedule: ""
suspend: false
successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 2
restartPolicy: OnFailure
backoffLimit: 1
