---
apiVersion: v1
kind: Service
metadata:
  name: jelu
spec:
  ports:
  - port: 11111
    protocol: TCP
    targetPort: http
  selector:
    app: jelu
  type: ClusterIP
  # if type: LoadBalancer is enabled than comment out INGRESS section below

