apiVersion: v1
kind: Service
metadata:
  name: {{ include "jelu.fullname" . }}
  labels:
    {{- include "jelu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "jelu.selectorLabels" . | nindent 4 }}
