annotations:
  artifacthub.io/changes: |-
    - kind: added
      description: Checksum of values added to the deployment to ensure config changes cause reload
apiVersion: v2
appVersion: v0.9.6
dependencies:
- name: common
  repository: https://bjw-s.github.io/helm-charts
  version: 1.5.1
description: Chart for Homepage
icon: https://github.com/gethomepage/homepage/blob/main/public/mstile-150x150.png
maintainers:
- name: jameswynn
name: homepage
sources:
- https://github.com/jameswynn/helm-charts/charts/homepage
- https://github.com/gethomepage/homepage/
version: 2.0.1
