apiVersion: v1
kind: ServiceAccount
metadata:
  name: metallb-speaker-restarter
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metallb-speaker-restarter
  namespace: metallb-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metallb-speaker-restarter
  namespace: metallb-system
subjects:
  - kind: ServiceAccount
    name: metallb-speaker-restarter
    namespace: metallb-system
roleRef:
  kind: Role
  name: metallb-speaker-restarter
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: metallb-speaker-restart
  namespace: metallb-system
spec:
  # Run every 15 minutes to refresh ARP announcements
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: metallb-speaker-restarter
          restartPolicy: OnFailure
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Restarting MetalLB speaker to refresh ARP announcements..."
                  kubectl delete pod -n metallb-system -l app.kubernetes.io/component=speaker
                  echo "Speaker pod deleted, will be recreated by DaemonSet"
