apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- convertx-deploy.yaml
images:
- name: c4illin/convertx
  newTag: v0.14.1
labels:
- includeSelectors: true
  pairs:
    app: convertx
