apiVersion: v1
kind: Service              # 1
metadata:
  name: sa-frontend-lb
  namespace: sa-ns
  # annotations:
  #   external-dns.alpha.kubernetes.io/hostname: "{{ appdomain }}"
  #   external-dns.alpha.kubernetes.io/ttl: "1"
  #   external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  type: LoadBalancer       # 2
  # if type: LoadBalancer is enabled than comment out INGRESS section below
  ports:
  - port: 80               # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: sa-frontend       # 7

# INGRESS
# cat << 'EOF' | kubectl apply -f -
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: "{{ appname }}"
#   namespace: "{{ appname }}"
#   annotations:
#     kubernetes.io/ingress.class: traefik
#     cert-manager.io/cluster-issuer: letsencrypt-staging
#     traefik.ingress.kubernetes.io/router.middlewares: default-my-basic-auth@kubernetescrd
# spec:
#   tls:
#     - secretName: "{{ appname }}"-home-local-tls
#       hosts:
#         - "{{ appdomain }}"
#   rules:
#   - host: "{{ appdomain }}" 
#     http:
#       paths:
#         - path: /
#           pathType: Prefix
#           backend:
#             service:
#               name: "{{ appname }}"
#               port:
#                 number: 80
#EOF