apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flaresolverr-deploy.yaml
- flaresolverr-svc.yaml
- flaresolverr-ing.yaml
images:
- name: ghcr.io/flaresolverr/flaresolverr
  newTag: v3.4.0
labels:
- includeSelectors: true
  pairs:
    app: flaresolverr
