---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-reflector
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/system/reflector/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
