---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  namespace: database
  annotations:
    coredns.io/hostname: postgres.garb.dev
    lbipam.cilium.io/ips: 192.168.40.11
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v16
    cnpg.io/instanceRole: primary
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-r
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v16
    cnpg.io/podRole: instance
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-ro
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v16
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-v16-rw
  namespace: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-v16
    role: primary
