---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-actions-runner-controller
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/arc-system/actions-runner-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-actions-runner-controller-runners
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/arc-system/actions-runner-controller/runners
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 30m
  dependsOn:
    - name: cluster-apps-actions-runner-controller
