---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-csi
  namespace: system
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-provision-csi
  resources:
    requests:
      storage: 500Gi
