---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: snmp-exporter
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SNMP_PASSWORD: |
          {{ .snmp_password }}
  data:
    - secretKey: snmp_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: snmp_pw
