---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./external-secret.yaml
  - ./helm-release.yaml
configMapGenerator:
  - name: snmp-exporter
    files:
      - snmp.yaml=./snmp.yml
generatorOptions:
  disableNameSuffixHash: true
