---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: txtdot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: txtdot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: txtdot
    spec:
      containers:
        - image: ghcr.io/txtdot/txtdot:latest
          name: txtdot
          ports:
            - containerPort: 8080
              protocol: TCP
              name: txtdot
          resources: {}
          volumeMounts:
            - mountPath: /app/.env
              name: txtdot-claim0
      restartPolicy: Always
      volumes:
        - name: txtdot-claim0
          persistentVolumeClaim:
            claimName: txtdot-claim0
