---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-networking-opnsense
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/main/apps/networking/opnsense/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
