---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-staging-cert
spec:
  secretName: ca-staging-tls-stage
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.garb.dev"
  dnsNames:
    - "*.garb.dev"
    - "garb.dev"
