apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prowlarr-deploy.yaml
- prowlarr-pvc.yaml
- prowlarr-svc.yaml
- prowlarr-ing.yaml
images:
- name: pmialon/prowlarr
  newTag: 2.0.5.5160
labels:
- includeSelectors: true
  pairs:
    app: prowlarr
