---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  labels:
    type: config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
status: {}
