---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/database/cloudnative-pg/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/database/cloudnative-pg/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: cluster-apps-cloudnative-pg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-backup
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/database/cloudnative-pg/backup"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: cloudnative-pg-cluster
