apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  #settings.yaml: ""
  settings.yaml: |
      color: neutral
      hideVersion: true
      iconStyle: theme
      layout:
      - Cloud:
          icon: mdi-cloud
      - Organization:
          icon: mdi-file-document-multiple-outline
      - Smart Home:
          icon: mdi-home-outline
      - Network:
          icon: mdi-lan
      - Media:
          icon: mdi-filmstrip-box
      - Indexer:
          icon: mdi-download-multiple
      - Downloader:
          icon: mdi-download-outline
      - Server:
          icon: mdi-server
      target: _self
      theme: dark
      title: Homelab
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Network:
        - Router:
            description: Router
            href: http://192.168.0.1
            icon: avmfritzbox.svg
            weight: 1
        - Pihole Home:
            description: DNS Server
            href: http://192.168.0.12
            icon: adguard-home.svg
            weight: 2
    - Server:
      - Portainer:
          description: Container Management
          href: https://localhost:9443
          icon: portainer.svg
          weight: 30
      - Proxmox:
          description: Promox Web UI
          href: https://192.168.0.10:8006
          icon: proxmox.svg
          weight: 41
      - Unifi:
          description: Unifi Controller
          href: https://hassio.home.adaminformatika.hu:8443/
          icon: unifi.svg
          weight: 42
      - Uptimekuma:
          description: uptimekuma
          href: http://uptimekuma.home.adaminformatika.hu/
          icon: uptimekuma.svg
          weight: 43
      - Netdata:
          description: Netdata
          href: https://app.netdata.cloud/spaces/adaminfo-space/rooms/all-nodes/
          icon: netdata.svg
          weight: 50
      - Hassio:
          description: Hassio
          href: http://hassio.home.adaminformatika.hu:8123/lovelace/default_view
          icon: homeassistant.svg
          weight: 60
      - Argocd:
          description: ArgoCD
          href: https://argocd.home.adaminformatika.hu/
          icon: argocd.svg
          weight: 70
      - Grafana:
          description: Grafana
          href: https://adaminfo.grafana.net/login/grafana_com
          icon: grafana.svg
          weight: 80
      - Netalertx:
          description: Netalertx
          href: http://192.168.0.11:20211/
          icon: netalertx.svg
          weight: 90
      - Resilio:
          description: Resilio-client
          href: https://127.0.0.1:8888/gui/
          icon: resilio.png
          weight: 100
    - Media:
      - Bazarr:
          description: Subtitle Management
          href: http://bazarr.home.adaminformatika.hu/
          icon: bazarr.png
          weight: 10
      - Qbittorrent:
          description: Torrent Client
          href: http://qbittorrent.home.adaminformatika.hu/
          icon: qbittorrent.png
          weight: 20
      - Sonarr:
          description: TV Shows
          href: http://sonarr.home.adaminformatika.hu/
          icon: sonarr.png
          weight: 30
      - Radarr:
          description: Movies
          href: http://radarr.home.adaminformatika.hu/
          icon: radarr.png
          weight: 40
      - Prowlarr:
          description: Prowlarr
          href: http://prowlarr.home.adaminformatika.hu/
          icon: prowlarr.png
          weight: 50
      - Plex:
          description: Plex
          href: http://plex.home.adaminformatika.hu/
          icon: plex.png
          weight: 60
      - Calibre:
          description: Calibre
          href: http://calibre.home.adaminformatika.hu/
          icon: calibre.png
          weight: 70
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
