apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: tools
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  #settings.yaml: ""
  settings.yaml: |
      color: neutral
      hideVersion: true
      iconStyle: theme
      layout:
      - Cloud:
          icon: mdi-cloud
      - Organization:
          icon: mdi-file-document-multiple-outline
      - Smart Home:
          icon: mdi-home-outline
      - Network:
          icon: mdi-lan
      - Media:
          icon: mdi-filmstrip-box
      - Indexer:
          icon: mdi-download-multiple
      - Downloader:
          icon: mdi-download-outline
      - Server:
          icon: mdi-server
      target: _self
      theme: dark
      title: Homelab
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Network:
        - Router:
            description: Router
            href: http://192.168.0.1
            icon: avmfritzbox.svg
        - Pihole Home:
            description: DNS Server
            href: http://192.168.0.12
            icon: adguard-home.svg
    - Server:
      - Portainer:
          description: Container Management
          href: https://localhost:9443
          icon: portainer.svg
      - Proxmox:
          description: Promox Web UI
          href: https://192.168.0.10:8006
          icon: proxmox.svg
      - Unifi:
          description: Unifi Controller
          href: https://hassio.home.adaminformatika.hu:8443/
          icon: unifi.svg
      - Uptimekuma:
          description: uptimekuma
          href: http://uptimekuma.home.adaminformatika.hu/
          icon: uptime-kuma.svg
          widget:
            type: uptimekuma
            url: http://uptimekuma.home.adaminformatika.hu/
            slug: home
            key: "{{UPTIMEKUMA_API_KEY}}"
      - Speedtest Tracker:
          icon: librespeed.svg
          href: https://speedtest-tracker.home.adaminformatika.hu/admin
          description: Internet Speed Test
          widget:
            type: speedtest
            url: https://speedtest-tracker.home.adaminformatika.hu/
            key: "{{SPEEDTEST_TRACKER_API_KEY}}"
      - Home assistant:
          description: Hassio
          href: http://hassio.home.adaminformatika.hu:8123/lovelace/default_view
          icon: home-assistant.svg
          widget:
            type: homeassistant
            url: http://hassio.home.adaminformatika.hu:8123
            key: "{{HASSIO_TRACKER_API_KEY}}"
            custom:
              - state: sensor.thermostat_temperature
              - state: lock.node_3
              - state: sensor.node_3_battery_level
      - Argocd:
          description: ArgoCD
          href: https://argocd.home.adaminformatika.hu/
          icon: argocd.svg
    - Media:
      - Qbittorrent:
          description: Torrent Client
          href: http://qbittorrent.home.adaminformatika.hu/
          icon: qbittorrent.png
  widgets.yaml: |
    - kubernetes:
        cluster:
          # Shows the cluster node
          show: true
          # Shows the aggregate CPU stats
          cpu: true
          # Shows the aggregate memory stats
          memory: true
          # Shows a custom label
          showLabel: true
          label: "cluster"
        nodes:
          # Shows the clusters
          show: true
          # Shows the CPU for each node
          cpu: true
          # Shows the memory for each node
          memory: true
          # Shows the label, which is always the node name
          showLabel: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
