apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- homepage-clusterrole.yaml
- homepage-cm.yaml
- homepage-deploy.yaml
- homepage-ing.yaml
- homepage-pvc.yaml
- homepage-secret.yaml
- homepage-service-account.yaml
- homepage-svc.yaml
images:
- name: ghcr.io/gethomepage/homepage
  newTag: v1.1.1
labels:
- includeSelectors: true
  pairs:
    app: homepage
