apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-cm.yaml

# helmGlobals:
#   chartHome: ../../../helm-charts

# helmCharts:
# - name: generic-service
#   releaseName: homepage
#   valuesFile: values.yaml
#   namespace: tools
#   version: 0.0.1

helmCharts:
- repo: https://jameswynn.github.io/helm-charts
  name: homepage
  version: 2.0.1
  releaseName: homepage
  valuesFile: values.yaml
  namespace: tools
