image:
  repository: "ghcr.io/gethomepage/homepage"
  tag: "v0.9.6@sha256:e5b2616d17db8961a53c0b7d389d812d31c265d35696d475732f53278c9276f7"

config:
  bookmarks: {}
  kubernetes:
    mode: cluster
  services:
  - Network:
    - FritzBox:
        description: Router
        href: http://192.168.0.1
        icon: avmfritzbox.svg
        weight: 1
    - AdGuard Home:
        description: Phihole
        href: http://192.168.0.12
        icon: adguard-home.svg
        weight: 2
  - Server:
    - "PVE01":
        description: Promox Web UI
        href: https://192.168.0.10:8006
        icon: proxmox.svg
        weight: 41
    - "Grafana":
        description: Grafana
        href: https://adaminfo.grafana.net/
        icon: grafana.svg
        weight: 42
  - Media:
    - Plex:
        app: plex
        description: Media Center
        href: https://app.plex.tv/desktop
        icon: plex.svg
        namespace: media-server
        weight: 1
        widget:
          type: tautulli
          url: http://172.16.1.1:8181
          key: aabbccddeeffgghhiijjkkllmmnnoo
  settings:
    color: neutral
    hideVersion: true
    iconStyle: theme
    layout:
    - Cloud:
        icon: mdi-cloud
    - Organization:
        icon: mdi-file-document-multiple-outline
    - Smart Home:
        icon: mdi-home-outline
    - Network:
        icon: mdi-lan
    - Media:
        icon: mdi-filmstrip-box
    - Indexer:
        icon: mdi-download-multiple
    - Downloader:
        icon: mdi-download-outline
    - Server:
        icon: mdi-server
    target: _self
    theme: dark
    title: Homelab
  widgets:
  - resources:
      backend: resources
      cpu: true
      expanded: true
      memory: true
  - search:
      provider: google
      target: _blank

ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    enabled: true
    hosts:
    - host: dashboard.home.adaminformatika.hu
      paths:
      - path: /
    ingressClassName: traefik
    tls:
    - hosts:
      - dashboard.home.adaminformatika.hu
      secretName: dashboard.home.adaminformatika.hu

enableRbac: true

serviceAccount:
  create: true
