image:
  repository: "ghcr.io/gethomepage/homepage"
  tag: "v0.9.6@sha256:e5b2616d17db8961a53c0b7d389d812d31c265d35696d475732f53278c9276f7"

config:
    bookmarks:
        - Developer:
              - Github:
                    - abbr: GH
                      href: https://github.com/
    services:
        - My First Group:
              - My First Service:
                    href: http://localhost/
                    description: Homepage is awesome

        - My Second Group:
              - My Second Service:
                    href: http://localhost/
                    description: Homepage is the best

        - My Third Group:
              - My Third Service:
                    href: http://localhost/
                    description: Homepage is 😎
    widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
        - kubernetes:
              cluster:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
                  label: "cluster"
              nodes:
                  show: true
                  cpu: true
                  memory: true
                  showLabel: true
        - search:
              provider: duckduckgo
              target: _blank
    kubernetes:
        mode: cluster
    settings:

# The service account is necessary to allow discovery of other services
serviceAccount:
    name: "homepage"
    create: true

# This enables the service account to access the necessary resources
enableRbac: true

service:
  main:
    ports:
      http:
        port: 3000

ingress:
  main:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    enabled: true
    hosts:
    - host: &host "dashboard.home.adaminformatika.hu"
      paths:
      - path: /
    ingressClassName: traefik
    tls:
    - hosts:
      - *host
      secretName: *host

