---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-credentials
  namespace: monitoring
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        access_key: "{{ .access_key }}"
        secret_key: "{{ .secret_key }}"
  refreshInterval: 15m
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cc47c52b-9c7f-489b-9537-b05e01151d8e
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: cc47c52b-9c7f-489b-9537-b05e01151d8e
        property: password
