---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-hass
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        HASS_GOOGLE_PROJECT_ID: |-
          {{ .hass_google_project_id }}
        HASS_POSTGRES_HOST: &dbHost postgres-v16-rw.database.svc
        HASS_POSTGRES_USER: &dbUser |-
          {{ .postgres_hass_user }}
        HASS_POSTGRES_PASSWORD: &dbPass |-
          {{ .postgres_hass_pass }}
        HASS_POSTGRES_URL: "postgresql://{{ .postgres_hass_user }}:{{ .postgres_hass_pass }}@postgres-v16-rw.database.svc.cluster.local/home_assistant"
        # Postgres Init
        INIT_POSTGRES_DBNAME: home_assistant
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .postgres_pw }}
  refreshInterval: 15m
  data:
    - secretKey: hass_google_project_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: hass_google_project_id
    - secretKey: postgres_hass_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_hass_user
    - secretKey: postgres_hass_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_hass_pass
    - secretKey: postgres_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_pw
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-secrets
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        prom-token: |-
          {{ .hass_prometheus_token }}
  refreshInterval: 15m
  data:
    - secretKey: hass_prometheus_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: hass_prometheus_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-home-assistant
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/home-assistant"
        RESTIC_PASSWORD: "{{ .restic_password }}"
  refreshInterval: 15m
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: minio-s3-endpoint
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: restic_password
