---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      #nodeSelector:
        #node-type: worker
      containers:
      - image: nginxdemos/hello@sha256:1b5efb2e43f1e788af78774060d76d6c49b81b81f627b0e7f25782618d932d7b
        name: hello-world
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "384Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          protocol: TCP
          name: hello-world
