---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
  labels:
    type: data
  name: data
spec:
  accessModes:
  - ${SC_DATA_MODE:=ReadWriteOnce}
  storageClassName: ${SC_DATA:=local-path}
  resources:
    requests:
      storage: ${SC_DATA_SIZE:=8Ti}
