apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- streetmerchant-deploy.yaml
- streetmerchant-ing.yaml
#- streetmerchant-pvc.yaml
- streetmerchant-svc.yaml
images:
- name: ghcr.io/jef/streetmerchant.io
  newTag: 3.9.0
labels:
- includeSelectors: true
  pairs:
    app: streetmerchant
