---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    app: dentari
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicmFkYW1odSIsInBhc3N3b3JkIjoiZ2hwX05HaGJLbThzQXdNUEx5RGJaRUF1eEJCcmtBSDVHRDNHQ2ciLCJhdXRoIjoiY21Ga1lXMW9kVHBuYUhCZlRrZG9Za3R0T0hOQmQwMVFUSGxFWWxwRlFYVjRRa0p5YTBGSU5VZEVNMGREWnc9PSJ9fX0=
