---
# GHCR Secret Template
# This file should NOT contain actual credentials.
#
# To create the secret manually:
#   kubectl create secret docker-registry ghcr-secret \
#     --docker-server=ghcr.io \
#     --docker-username=<your-github-username> \
#     --docker-password=<your-github-token> \
#     --docker-email=<your-email>
#
# For production, use one of these secure methods:
# 1. Sealed Secrets: https://github.com/bitnami-labs/sealed-secrets
# 2. External Secrets Operator: https://external-secrets.io/
# 3. ArgoCD Vault Plugin: https://argocd-vault-plugin.readthedocs.io/
#
# Example using Sealed Secrets:
#   kubectl create secret docker-registry ghcr-secret \
#     --docker-server=ghcr.io \
#     --docker-username=<username> \
#     --docker-password=<token> \
#     --dry-run=client -o yaml | \
#     kubeseal -o yaml > ghcr-sealed-secret.yaml
#
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    app: dentari
type: kubernetes.io/dockerconfigjson
data:
  # DO NOT commit actual credentials here!
  # Create this secret using kubectl or a secret management solution
  .dockerconfigjson: ""
