---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litestream-secrets
  namespace: dentari
spec:
  encryptedData:
    access-key-id: AgCTYqlOmh000LRuwFgGvt6icqbAOR4lCyqh2LMLtaDG88yzcUlIo4VvLqdq7CwANvpKy9EIbsinQNvWeZWOiDjbuD6hW0oUUJ038mTx3bhupBvcMCWiBmVTUNbZ7ZRW2Fe65cMxQZQkHcA1Xh6P2LFFaQkM3yYCG3fYouO2AYrxc1EGqzELxNlonBXv2V93HixGu02+9RmpxZJJw10r3zhvQLGbJMbXTuAg3ht/TozYmrsUUUgkzLu4OFO2wAcJV/nbtBQGruxwzIeBE7VhyrgA47rOCuJLkPLiWPy+e7C+PYvq8h0S/yCpf/85vkwfAk5IWN+nZuo+5awN+/hWnR/Gxxenoqhclw32XDoASNFdFnhlKgBtVvCehFSWxmkf/iBcOjzS/ratY/oXAeKOniIVQhxaxVq3zcZONWKsuZYpg5aYFRdK2asOQmtVIK/i4abv7uzEf1cmWFgNUxeiP8IFw8kqBOxafidCCWv/257ow6IuyR4LgNy3KnbIQuSnkjeu8zNfGYG/vHEEGSefiH7ia+8mbOHqT71jFkC9PCoUT7Onu8D4KCC1kdFV69Ep0YCoMHnHaua2rEnSM9XSpOi83CYxSFGCad0nZN/yHIIr6ahnkPZlfdnwFdtzzmWwY+WNKg+EU9DGkFn1FCXY36SW+VHq1Yc9+KZMXjvykE1ZUEDxcGEzaK91eZ39xmq9YpwMYRy1rfNqf9TI+RXC5gaArBwUwBQ0YUpKkBkDXP2mNg==
    secret-access-key: AgCmzxI6H8OTF1ldCv2dryvXS0SO9PmIMmmqG9doEeNSK3YGfeKqvh2kaIKB3J3ujB7fDN3ak9uzgq+uq/9wUPVZzWj2icmF5Frvc6RUgcKy6KvgDspHlHrFb+vwrjRXwmn9IDQ7gz6Qxo7MzCSLcSgZLAkKKdz/LdLOUTEMjynrGzTTaEnD+ihOa3hZpOCLOLVxJ0tYcaGto0xQ0C2yWpGKWlq6gVYK8SZXEGL58m9aRbxn7lArazTgXD0n0OoJpR07tzvVxbHIj4fm3oNxPU7K3QA8ZJeSAKkqbsah4s7MqTTKUUnIjqc0Iu5lNyz7y4RQ3txqVf1UVlIX4ZbyPzKTagqAPP6pzB9FChAnMuWkoDXJ1rdoKsbS9m/oBjbFTAE2LVpxdBzRkkOumExMoSwotMjibNEMBBR6lXwUROQJ+aQru7cNq7CVktwJqZ6ROdWSZo90PxBWotuVnIawxNnSAx56h7SHlQH8ejgFPqwX2cK79N6r/zPffgqvRPpT6bj2TIF8O5ibjoayFV3LZXC/Tw92N4vaWfdbz0yDvGhRcUlK7JnNjzg1L4s5LvSfp6w0OzdU8/7/PDLW85KlBccMUwWfHOpq4MeLq3CAhIPjIJ/8sbtxbl+u5kCgHm1+z/oqW1+SH9TOzw5L1ZmRIUWJgLhuEqRraLKmrkeFOZxuZGle7rSKQjeQSzDYczPqVVZnuMUkCU4yxQp8wpILYMuopKSeS9zHSkbDDi+6aPTfKu2Z+SUjaehB27wO4E/2gr5eZN5+sbCG0uY/mozdDen4
  template:
    metadata:
      creationTimestamp: null
      name: litestream-secrets
      namespace: dentari
