---
apiVersion: batch/v1
kind: Job
metadata:
  name: dentari-migrate-schema
  namespace: dentari
  labels:
    app: dentari
    component: migrate-schema-job
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: dentari
        component: migrate-schema-job
    spec:
      restartPolicy: OnFailure
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: migrate-schema
          image: ghcr.io/radamhu/dentari:latest
          imagePullPolicy: Always
          command:
            - "python"
            - "-c"
            - |
              import sqlite3

              db_path = "/app/data/dentari.db"
              print(f"🔄 Migrating database schema at {db_path}...")

              conn = sqlite3.connect(db_path)
              cursor = conn.cursor()

              # Check current schema
              print("\n📋 Checking current users table schema...")
              cursor.execute("PRAGMA table_info(users)")
              current_columns = {row[1] for row in cursor.fetchall()}
              print(f"  Current columns: {current_columns}")

              # Migration: Remove courier_name, add vehicle_type and phone
              if 'courier_name' in current_columns and 'vehicle_type' not in current_columns:
                  print("\n🔄 Migrating from old schema to new unified schema...")

                  # Step 1: Create new columns
                  print("  ➤ Adding vehicle_type column...")
                  cursor.execute("ALTER TABLE users ADD COLUMN vehicle_type TEXT")

                  print("  ➤ Adding phone column...")
                  cursor.execute("ALTER TABLE users ADD COLUMN phone TEXT")

                  # Step 2: Migrate courier_name data to name field if empty
                  print("  ➤ Migrating courier_name data...")
                  cursor.execute("""
                      UPDATE users
                      SET name = courier_name
                      WHERE role = 'courier' AND (name IS NULL OR name = '')
                  """)
                  migrated = cursor.rowcount
                  print(f"    Migrated {migrated} courier names")

                  # Step 3: We cannot drop courier_name column in SQLite
                  # SQLite doesn't support DROP COLUMN before version 3.35.0
                  # Just leave it for backwards compatibility
                  print("  ℹ️  Note: courier_name column kept for backwards compatibility")

                  conn.commit()
                  print("\n✅ Migration completed successfully!")

              elif 'vehicle_type' in current_columns and 'phone' in current_columns:
                  print("✅ Schema is already up to date, no migration needed.")
              else:
                  print("⚠️  Unknown schema state, manual intervention may be required")
                  print(f"   Columns found: {current_columns}")

              # Display final schema
              print("\n📋 Final users table schema:")
              cursor.execute("PRAGMA table_info(users)")
              for row in cursor.fetchall():
                  print(f"  {row[1]:20} {row[2]:10} {'NOT NULL' if row[3] else ''}")

              # Display users
              print("\n👥 Current users in database:")
              cursor.execute("SELECT username, name, role, vehicle_type, phone, is_active FROM users")
              for row in cursor.fetchall():
                  vehicle = f" | {row[3]}" if row[3] else ""
                  phone = f" | {row[4]}" if row[4] else ""
                  active = "✅" if row[5] else "❌"
                  print(f"  {active} {row[0]:12} | {row[1]:25} | {row[2]:12}{vehicle}{phone}")

              conn.close()
              print("\n✅ Migration check complete!")
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          volumeMounts:
            - name: data
              mountPath: /app/data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dentari-data-pvc
      imagePullSecrets:
        - name: ghcr-secret
