---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dentari-data-pvc
  labels:
    app: dentari
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dentari-cache-pvc
  labels:
    app: dentari
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dentari-logs-pvc
  labels:
    app: dentari
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
