---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/database/dragonfly/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: dragonfly
  path: ./kubernetes/main/apps/database/dragonfly/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
