---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-gateway-manifest
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/networking/gateway/cilium"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/networking/gateway/envoy/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-manifests
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/networking/gateway/envoy/manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: envoy
