kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  annotations:
    name: prowlarr
    namespace: prowlarr
    annotations:
     kubernetes.io/ingress.class: traefik
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # traefik.ingress.kubernetes.io/router.middlewares: default-my-basic-auth@kubernetescrd
  labels:
    app: prowlarr
spec:
  # tls:
  #   - secretName: "{{ appname }}"-home-local-tls
  #     hosts:
  #       - "{{ appdomain }}"
    rules:
  - host: prowlarr.home.adaminformatika.hu
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prowlarr
              port:
                number: 9696
