---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flaresolverr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: CAPTCHA_SOLVER
              value: "none"
            - name: LOG_HTML
              value: "false"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 8191
              name: flaresolverr-8191
              protocol: TCP
          resources: {}
      restartPolicy: Always
