---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr@sha256:5f5661db1e69a6f80ac24d47d9fa5580f6f741ee5ec967818396ae0dacecd7ea
          ports:
            - containerPort: 8191
              name: flaresolverr
              protocol: TCP
          resources: {}
      restartPolicy: Always
