version = 0.1
[default.deploy.parameters]
stack_name = "grafana-sms-notifier"
resolve_s3 = true
s3_prefix = "grafana-sms-notifier"
region = "eu-central-1"
profile = "saml"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
