---
apiVersion: v1
kind: Service
metadata:
  name: openfaas
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: openfaas
  type: LoadBalancer
  # if type: LoadBalancer is enabled than comment out INGRESS section below
status:
  loadBalancer: {}
