---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./blocky/ks.yaml
  - ./cloudflared/ks.yaml
  - ./ddns/ks.yaml
  - ./external-dns/ks.yaml
  - ./gateway/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./opnsense/ks.yaml
  - ./tailscale-gateway/ks.yaml
