apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- n8n-deploy.yaml
- n8n-pvc.yaml
- n8n-svc.yaml
- n8n-ing.yaml
images:
- name: n8nio/n8n
  newTag: 1.101.1
labels:
- includeSelectors: true
  pairs:
    app: n8n
