apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-dentari
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  destination:
    namespace: dev-dentari
    server: "https://kubernetes.default.svc"
  source:
    path: argocd-apps/demo/dev-dentari
    repoURL: "https://github.com/radamhu/argocd"
    targetRevision: main

  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - Prune=true
    retry:
      limit: 10
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 15m
