---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-external
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/networking/ingress-nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-internal
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/networking/ingress-nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
