---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
  labels:
    app.kubernetes.io/name: cloudflared
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.yaml: |
    ---
    tunnel: ${SECRET_CLOUDFLARE_TUNNEL}

    credentials-file: /etc/cloudflared/creds.json

    originRequest:
      http2Origin: true
      originServerName: ingress.garb.dev

    no-autoupdate: true

    ingress:
    - hostname: "files.garb.dev"
      service: https://ingress-external-ingress-nginx-controller.networking.svc.cluster.local:443
    - hostname: "photos.garb.dev"
      service: https://ingress-external-ingress-nginx-controller.networking.svc.cluster.local:443
    - hostname: "echo-envoy.garb.dev"
      service: https://envoy-networking-envoy-external-45a7c13f.networking.svc.cluster.local:443
    - hostname: "*-cilium.garb.dev"
      service: https://cilium-gateway-cilium-external.networking.svc.cluster.local:443
    - hostname: "*.garb.dev"
      service: https://envoy-networking-envoy-external-45a7c13f.networking.svc.cluster.local:443
    - service: http_status:404
