---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-creds
  namespace: networking
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        CLOUDFLARE_TUNNEL_ID: "{{ .cloudflare_tunnel }}"
        creds.json: |-
          {{ .cloudflared_json }}
  refreshInterval: 15m
  data:
    - secretKey: cloudflared_json
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: 1e657173-c178-4960-baa0-b17e00eced5d
    - secretKey: cloudflare_tunnel
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: cloudflare_tunnel
