apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sonarr-deploy.yaml
- sonarr-pvc.yaml
- sonarr-svc.yaml
- sonarr-ing.yaml
images:
- name: pmialon/sonarr
  newTag: 4.0.14.2939
labels:
- includeSelectors: true
  pairs:
    app: sonarr
