apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- uptimekuma-deploy.yaml
- uptimekuma-pvc.yaml
- uptimekuma-svc.yaml
- uptimekuma-ing.yaml
images:
- name: louislam/uptime-kuma
  newTag: 1.23.16
labels:
- includeSelectors: true
  pairs:
    app: uptimekuma
