---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptimekuma
  labels:
    type: config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
status: {}
