---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-blocky
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/networking/blocky/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
        optional: false
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: dragonfly
