version: "3"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest@sha256:e46f9b5daf0435c24b238211c06b3fb669830a464ef2b8538328332ff48206a3 
    container_name: qbittorrent 
    hostname: qbittorrent 
    networks: 
      - mediarr 
    environment: 
      - PUID=1000 
      - PGID=100 
      - TZ=Africa/Casablanca 
      - WEBUI_PORT=8080 
    volumes: 
      - ./configs/mediarr/qbittorrent:/config 
      - myDlFolders:/downloads 
    ports: 
      - 8080:8080 
      - 6881:6881 
      - 6881:6881/udp 
    restart: unless-stopped 