apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: qbittorrent
spec:
  ports:
    - name: qbittorrent-8080
      port: 8080
      targetPort: 8080
    - name: qbittorrent-6881
      port: 6881
      targetPort: 6881
  selector:
    app: qbittorrent
  type: LoadBalancer
  # if type: LoadBalancer is enabled than comment out INGRESS section below
status:
  loadBalancer: {}

# https://www.reddit.com/r/kubernetes/comments/uqrss9/cant_expose_connect_to_qbittorrent_deployment/
# https://metallb.universe.tf/usage/
# Metallb IP Address Sharing
# apiVersion: v1
# kind: Service
# metadata:
#   name: qbittorrent
#   # annotations:
#   #   metallb.universe.tf/allow-shared-ip: qbittorrent
# spec:
#   ports:
#     - name: qbittorrent-8080
#       port: 8080
#       targetPort: 8080
#     - name: qbittorrent-6881-udp
#       port: 6881
#       targetPort: 6881
#   selector:
#     app: qbittorrent
#   type: LoadBalancer
#   # if type: LoadBalancer is enabled than comment out INGRESS section below
# status:
#   loadBalancer: {}