apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://stakater.github.io/stakater-charts
    chart: reloader
    targetRevision: 1.2.0
    helm:
      values: |
        reloader:
          watchGlobally: true
          # Reload strategy: "env-vars" (default) or "annotations"
          # Use "annotations" for better GitOps compatibility with ArgoCD
          reloadStrategy: annotations
          deployment:
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                cpu: 100m
                memory: 128Mi
          # Optional: Enable logging in JSON format
          logFormat: json
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
