---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ./helm-release.yaml
configMapGenerator:
  - name: strip-port-from-host
    files:
      - ./config/main.lua
generatorOptions:
  disableNameSuffixHash: true
