version: "3"
services:
  plex:
    image: plexinc/pms-docker@sha256:55a784815837ea534c8caf95d586e838e37a608fc2c1017e3295802e7f62c354
    restart: unless-stopped
    container_name: plexms
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/London
      - PLEX_CLAIM=claim-<your-string>

    volumes:
      - ${USERDIR}/docker/plexms/config:/config
      - ${USERDIR}/docker/plexms/transcodes:/transcode
      - ${USERDIR}/docker/plexms/media:/media