apiVersion: v1
kind: Service
metadata:
  name: plex
  # annotations:
  #   metallb.universe.tf/allow-shared-ip: qbittorrent
spec:
  ports:
    - name: "32400"
      port: 32400
      targetPort: 32400
    - name: "3005"
      port: 3005
      targetPort: 3005
    - name: "8324"
      port: 8324
      targetPort: 8324
    - name: "32469"
      port: 32469
      targetPort: 32469
    - name: "1900"
      port: 1900
      protocol: UDP
      targetPort: 1900
    - name: "32410"
      port: 32410
      protocol: UDP
      targetPort: 32410
    - name: "32412"
      port: 32412
      protocol: UDP
      targetPort: 32412
    - name: "32413"
      port: 32413
      protocol: UDP
      targetPort: 32413
    - name: "32414"
      port: 32414
      protocol: UDP
      targetPort: 32414
  selector:
    app: plex
status:
  loadBalancer: {}

# https://www.reddit.com/r/kubernetes/comments/uqrss9/cant_expose_connect_to_qbittorrent_deployment/
# https://metallb.universe.tf/usage/
# Metallb IP Address Sharing
# apiVersion: v1
# kind: Service
# metadata:
#   name: qbittorrent
#   # annotations:
#   #   metallb.universe.tf/allow-shared-ip: qbittorrent
# spec:
#   ports:
#     - name: qbittorrent-8080
#       port: 8080
#       targetPort: 8080
#     - name: qbittorrent-6881-udp
#       port: 6881
#       targetPort: 6881
#   selector:
#     app: qbittorrent
#   type: LoadBalancer
#   # if type: LoadBalancer is enabled than comment out INGRESS section below
# status:
#   loadBalancer: {}