apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - env:
            - name: PGID
            - name: PLEX_CLAIM
              value: claim-<your-string>
            - name: PUID
            - name: TZ
              value: Europe/Budapest
          image: plexinc/pms-docker
          name: plexms
          ports:
            - containerPort: 32400
            - containerPort: 3005
            - containerPort: 8324
            - containerPort: 32469
            - containerPort: 1900
              protocol: UDP
            - containerPort: 32410
              protocol: UDP
            - containerPort: 32412
              protocol: UDP
            - containerPort: 32413
              protocol: UDP
            - containerPort: 32414
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: plex-claim0
            - mountPath: /transcode # The mountpoint inside the container
              name: nfs-vol
            - mountPath: /media # The mountpoint inside the container
              name: nfs-vol
      restartPolicy: Always
      volumes:
        - name: plex-claim0
          persistentVolumeClaim:
            claimName: plex-claim0
        - name: nfs-vol
          nfs:
            server: 192.168.0.21 # IP to our NFS server
            path: /media/ # The path to our NFS share # The exported directory
status: {}
