---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        mosquitto.conf: |-
          listener 1883
          persistence true
          persistence_location /mosquitto/data
          connection_messages false
          password_file /mosquitto/config/mosquitto_pwd
          autosave_interval 60
        mosquitto_pwd: |-
          {{ .mosquitto_pw }}
  refreshInterval: 15m
  data:
    - secretKey: mosquitto_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: mosquitto_pw
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-mosquitto
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/mosquitto"
        RESTIC_PASSWORD: "{{ .restic_password }}"
  refreshInterval: 15m
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: minio-s3-endpoint
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: restic_password
