---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: emby-config
    labels:
      type: emby-config
    namespace: media-server
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: local-path
    resources:
      requests:
        storage: 1Gi
