apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - emby-pvc.yaml
  - emby-svc.yaml
  - emby-deploy.yaml
  - emby-ing.yaml
images:
- name: docker.io/emby/embyserver
  newTag: 4.9.1.14
labels:
- includeSelectors: true
  pairs:
    app: emby
