---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: tailscale-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        TS_AUTHKEY: "{{ .auth_key }}?ephemeral=false&preauthorized=true"
  refreshInterval: 15m
  data:
    - secretKey: auth_key
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: tailscale_auth_key
