---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - prod-master-1
      nodeSelector:
        kubernetes.io/hostname: prod-master-1
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
        - image: linuxserver/lidarr
          name: lidarr
          imagePullPolicy: Always
          resources:
            limits: # you restrict the maximum amount of memory available to the pods
              memory: "1024M"
              cpu: "500m"
            requests: # allow you to allocate a guaranteed minimum of computing resources for the pods r
              memory: "256M"
              cpu: "250m"
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /downloads # The mountpoint inside the container
              name: nfs-vol
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr
        - name: nfs-vol
          nfs:
            server: 192.168.0.21 # IP to our NFS server
            path: /media/ # The path to our NFS share # The exported directory
status: {}
