---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-monitoring-opnsense
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/main/apps/monitoring/opnsense/manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: kube-prometheus-stack
      namespace: flux-system
