---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        mqtt_password: |-
          {{ .mqtt_password }}
        rtsp_user: |-
          {{ .rtsp_user }}
        rtsp_password: |-
          {{ .rtsp_password }}
  refreshInterval: 15m
  data:
    - secretKey: mqtt_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: mqtt_password
    - secretKey: rtsp_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: rtsp_user
    - secretKey: rtsp_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: rtsp_password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-frigate
  namespace: home
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/frigate"
        RESTIC_PASSWORD: "{{ .restic_password }}"
  refreshInterval: 15m
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: minio-s3-endpoint
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: restic_password
