---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  path: ./kubernetes/main/apps/system/local-path-provisioner/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
