---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SECRET_CLOUDFLARE_TOKEN: |-
          {{ .cloudflare_token }}
        SECRET_CLOUDFLARE_TUNNEL: |-
          {{ .cloudflare_tunnel }}
        SECRET_GRAFANA_PASSWORD: |-
          {{ .grafana_password }}
        SECRET_DOMAIN: |-
          {{ .domain }}
        SECRET_EMAIL: |-
          {{ .email }}
  refreshInterval: 15m
  data:
    - secretKey: cloudflare_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: cloudflare_token
    - secretKey: cloudflare_tunnel
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: cloudflare_tunnel
    - secretKey: grafana_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: grafana_password
    - secretKey: domain
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: domain
    - secretKey: email
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: email
