apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- radarr-deploy.yaml
- radarr-pvc.yaml
- radarr-svc.yaml
- radarr-ing.yaml
images:
- name: pmialon/backup-manager
  newTag: 0.7.14-1.3
- name: pmialon/radarr
  newTag: 5.9.1.9070
labels:
- includeSelectors: true
  pairs:
    app: radarr
