kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: radarr
  namespace: radarr
  annotations:
     kubernetes.io/ingress.class: traefik
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # traefik.ingress.kubernetes.io/router.middlewares: default-my-basic-auth@kubernetescrd
  labels:
    app: radarr
spec:
  # tls:
  #   - secretName: "{{ appname }}"-home-local-tls
  #     hosts:
  #       - "{{ appdomain }}"
  rules:
  - host: radarr.home.adaminformatika.hu
    http:
      paths:
        - path: /radarr
          pathType: Prefix
          backend:
            service:
              name: radarr
              port:
                number: 7878