---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - image: lscr.io/linuxserver/radarr:latest
          name: radarr
          ports:
            - containerPort: 7878
              name: radarr-7878
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: radarr-claim0
            - mountPath: /movies
              name: radarr-claim1
            - mountPath: /downloads
              name: radarr-claim2
      restartPolicy: Always
      volumes:
        - name: radarr-claim0
          persistentVolumeClaim:
            claimName: radarr-claim0
        - name: radarr-claim1
          persistentVolumeClaim:
            claimName: radarr-claim1
        - name: radarr-claim2
          persistentVolumeClaim:
            claimName: radarr-claim2
