---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bedroompi-ui
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/default/bedroompi/ui"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bedroompi-api
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/default/bedroompi/api"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
