---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streetmerchant
  labels:
    type: datastore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
