---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 10m
  path: "./kubernetes/main/apps/monitoring/prometheus-operator-crds/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: false
