apiVersion: v1
kind: Service
metadata:
  name: txtdot
spec:
  selector:
    app: txtdot
  ports:
    - name: txtdot-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  # if type: LoadBalancer is enabled than comment out INGRESS section below
