---
apiVersion: v1
kind: Service
metadata:
  name: changedetection
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: changedetection
  type: LoadBalancer
  # if type: LoadBalancer is enabled than comment out INGRESS section below
status:
  loadBalancer: {}
