apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- changedetection-deploy.yaml
- changedetection-ing.yaml
- changedetection-pvc.yaml
- changedetection-svc.yaml
images:
- name: ghcr.io/dgtlmoon/changedetection.io
  newTag: 0.49.7
labels:
- includeSelectors: true
  pairs:
    app: changedetection
