---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-lidarr
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/default/lidarr/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: cluster-apps-external-secrets-stores
