apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
  namespace: sa-ns
  labels:
    app: sa-frontend
spec:
  selector:
    matchLabels:
      app: sa-frontend
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      #nodeSelector:
        #node-type: worker
      containers:
        - image: radam/sentiment-analysis-frontend
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
