apiVersion: batch/v1
kind: CronJob
metadata:
  name: 'myjob'
  labels:
    app: 'myjob'
spec:
  schedule: "30 2 * * *"
  timeZone: 'Europe/Budapest'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: myimage
              image: docker.io/myimage:v0.1.1