apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- plex-deploy.yaml
- plex-ing.yaml
- plex-pvc.yaml
- plex-svc.yaml
- cors-middleware.yaml
images:
- name: linuxserver/plex
  newTag: 1.40.4
labels:
- includeSelectors: true
  pairs:
    app: plex

# generators:
# - ./generators/secrets-generator.yaml

# patchesStrategicMerge:
# - ./patches/pvc-plex-data.yaml

# configMapGenerator:
# - name: plex-env-vars
#   literals:
#   - TZ=America/Toronto
#   - ADVERTISE_IP=https://plex.tdude.co/
# - name: mediaserver-permissions
#   literals:
#   - PUID=1014
#   - PGID=1015
