apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - plex-pvc.yaml
  - plex-svc.yaml
  - plex-deploy.yaml
  - plex-ing.yaml
images:
- name: docker.io/plexinc/pms-docker
  newTag: 1.40.2.8395-c67dce28e
labels:
- includeSelectors: true
  pairs:
    app: plex
