---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media-server
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
      containers:
      - name: plex
        image: "docker.io/plexinc/pms-docker:1.40.2.8395-c67dce28e"
        imagePullPolicy: Always
        resources: {}
        env:
        - name: ADVERTISE_IP
          value: http://192.168.0.180/
        - name: PLEX_CLAIM
          value: claim-iHD5wyqT2SKfs2CBy87K
        - name: HOSTNAME
          value: "k8sPlex"
        - name: VERSION
          value: "docker"
        - name: PUID
          value: "0"
        - name: PGID
          value: "0"
        volumeMounts:
        - name: plex-config
          mountPath: /config
        - name: nfs-vol
          mountPath: /downloads # The mountpoint inside the container
      restartPolicy: Always
      volumes:
        - name: plex-config
          persistentVolumeClaim:
            claimName: plex-config
        - name: nfs-vol
          nfs:
            server: 192.168.0.21 # IP to our NFS server
            path: /media/ # The path to our NFS share # The exported directory
