---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-gateway-metrics
  namespace: networking
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-helm
  namespaceSelector:
    matchNames:
      - networking
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      honorLabels: true
