---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard-password
  namespace: rook-ceph
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  refreshInterval: 15m
  data:
    - secretKey: password
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 04f751aa-6570-4118-93f2-b1190023a181
        property: password
