---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sops-age
  namespace: infrastructure
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        age.key: |-
          {{ .age }}
  refreshInterval: 15m
  data:
    - secretKey: age
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: cb74d21d-81ae-462f-acf5-b05d01565917
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tfe-cli-config
  namespace: infrastructure
spec:
  target:
    name: tfe-cli-config
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        terraform.tfrc: |-
          credentials "app.terraform.io" {
            token = "{{ .terraform_cloud_token }}"
          }
  refreshInterval: 15m
  data:
    - secretKey: terraform_cloud_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: terraform_cloud_token
