apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tautulli-deploy.yaml
- tautulli-ing.yaml
- tautulli-pvc.yaml
- tautulli-svc.yaml
images:
- name: ghcr.io/tautulli/tautulli
  newTag: v2.15.2
labels:
- includeSelectors: true
  pairs:
    app: tautulli
