---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nvidia-dcgm-exporter
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/kube-system/nvidia/dcgm-exporter/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: cluster-apps-node-feature-discovery
