homepage:
  image:
    repository: "ghcr.io/gethomepage/homepage"
    tag: "v0.10.2@sha256:ef3c14d406a513eab1b9839a3b6a3bd189c315a1133b5b522d139e22f8bedc25"

  config:
    bookmarks:
      - Developer:
          - Github:
              - abbr: GH
                href: https://github.com/
    services:
    - Network:
        - Router:
            description: Router
            href: http://192.168.0.1
            icon: avmfritzbox.svg
            weight: 1
        - Pihole Home:
            description: DNS Server
            href: http://192.168.0.12
            icon: adguard-home.svg
            weight: 2
            widget:
              type: pihole
              url: http://192.168.0.12
              version: 6 # required if running v6 or higher, defaults to 5
              key: "{{PIHOLE_KEY}}" # optional
    - Server:
      - Portainer:
          description: Container Management
          href: https://localhost:9443
          icon: portainer.svg
          weight: 30
          widget:
            type: portainer
            url: https://localhost:9443
            env: 1
            key: ptr_accesskeyaccesskeyaccesskeyaccesskey
      - Proxmox:
          description: Promox Web UI
          href: https://192.168.0.10:8006
          icon: proxmox.svg
          weight: 41
          widget:
            type: proxmox
            url: https://192.168.0.10:8006
            username: api_token_id
            password: api_token_secret
            node: pve-1 # optional
      - Unifi:
          description: Unifi Controller
          href: https://hassio.home.local:8443/
          icon: unifi.svg
          weight: 42
          widget:
            type: unifi
            url: https://hassio.home.local:8443/
            username: username
            password: password
            site: Site Name # optional
      - Netdata:
          description: Netdata
          href: https://app.netdata.cloud/spaces/adaminfo-space/rooms/all-nodes/
          icon: netdata.svg
          weight: 50
          widget:
            type: netdata
            url: https://app.netdata.cloud/spaces/adaminfo-space/
      - Hassio:
          description: Hassio
          href: http://hassio.home.local:8123/lovelace/default_view
          icon: homeassistant.svg
          weight: 60
          widget:
            type: homeassistant
            url: http://hassio.home.local:8123/lovelace/default_view
            key: access_token
            custom:
              - state: sensor.total_power
              - state: sensor.total_energy_today
                label: energy today
              - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
                label: switches on
              - state: weather.forecast_home
                label: wind speed
                value: "{attributes.wind_speed} {attributes.wind_speed_unit}"
      - Argocd:
          description: ArgoCD
          href: https://argocd.home.adaminformatika.hu/
          icon: argocd.svg
          weight: 70
          widget:
            type: argocd
            url: https://argocd.home.adaminformatika.hu/
            key: argocd-token
      - Grafana:
          description: Grafana
          href: https://adaminfo.grafana.net/login/grafana_com
          icon: grafana.svg
          weight: 80
          widget:
            type: grafana
            url: https://adaminfo.grafana.net/login/grafana_com
            key: apikeyapikeyapikeyapikeyapikey
    - Media:
      - Tautulli:
          icon: tautulli
          href:
          container: tautulli
          widget:
            type: tautulli
            url:
            key: #api-key
      - Bazarr:
          description: Subtitle Management
          href: http://bazarr.home.adaminformatika.hu/
          icon: bazarr.png
          weight: 10
          widget:
            type: bazarr
            url: http://bazarr.home.adaminformatika.hu/
            key: apikeyapikeyapikeyapikeyapikey
      - Qbittorrent:
          description: Torrent Client
          href: http://qbittorrent.home.adaminformatika.hu/
          icon: qbittorrent.png
          weight: 20
      - Sonarr:
          description: TV Shows
          href: http://sonarr.home.adaminformatika.hu/
          icon: sonarr.png
          weight: 30
          widget:
            type: sonarr
            url: http://sonarr.home.adaminformatika.hu/
            key: 7621a07a286649f0b6436e9b0397c7ea
            enableQueue: true # optional, defaults to false
      - Radarr:
          description: Movies
          href: http://radarr.home.adaminformatika.hu/
          icon: radarr.png
          weight: 40
          widget:
            type: radarr
            url: http://radarr.home.adaminformatika.hu/
            key: apikeyapikeyapikeyapikeyapikey
            enableQueue: true # optional, defaults to false
      - Prowlarr:
          description: Prowlarr
          href: http://prowlarr.home.adaminformatika.hu/
          icon: prowlarr.png
          weight: 50
          widget:
            type: prowlarr
            url: http://prowlarr.home.adaminformatika.hu/
            key: apikeyapikeyapikeyapikeyapikey
      - Plex:
          description: Plex
          href: http://plex.home.adaminformatika.hu/
          icon: plex.png
          weight: 60
          widget:
            type: plex
            url: http://plex.home.adaminformatika.hu/
            key: mytokenhere # see https://www.plexopedia.com/plex-media-server/general/plex-token/
    settings:
      color: neutral
      hideVersion: true
      iconStyle: theme
      layout:
      - Cloud:
          icon: mdi-cloud
      - Organization:
          icon: mdi-file-document-multiple-outline
      - Smart Home:
          icon: mdi-home-outline
      - Network:
          icon: mdi-lan
      - Media:
          icon: mdi-filmstrip-box
      - Indexer:
          icon: mdi-download-multiple
      - Downloader:
          icon: mdi-download-outline
      - Server:
          icon: mdi-server
      target: _self
      theme: dark
      title: Homelab
    widgets:
        # show the kubernetes widget, with the cluster summary and individual nodes
      - kubernetes:
          cluster:
            show: true
            cpu: true
            memory: true
            showLabel: true
            label: "cluster"
          nodes:
            show: true
            cpu: true
            memory: true
            showLabel: true
      - search:
          provider: google
          target: _blank
    kubernetes:
        mode: cluster


  # The service account is necessary to allow discovery of other services
  serviceAccount:
      name: "homepage"
      create: true

  # This enables the service account to access the necessary resources
  enableRbac: true

  service:
    main:
      ports:
        http:
          port: 3000

  ingress:
    main:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      enabled: true
      hosts:
      - host: &host "dashboard.home.adaminformatika.hu"
        paths:
        - path: /
      ingressClassName: traefik
      tls:
      - hosts:
        - *host
        secretName: *host


  controllers:
    # Configure the main controller
    main:
      containers:
        env:
          PIHOLE_KEY:
            valueFrom:
              secretKeyRef:
                key: tools-ns-sealed-secret
                name: pihole_key
          SONARR-API:
            valueFrom:
              secretKeyRef:
                key: tools-ns-sealed-secret
                name: sonarr-api



