apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- scraperr-deploy.yaml
- scraperr-ing.yaml
- scraperr-pvc.yaml
- scraperr-svc.yaml
images:
- name: jpyles0524/scraperr
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app: scraperr
