---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
  namespace: database
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: |-
          {{ .postgres_user }}
        password: |-
          {{ .postgres_pw }}
  refreshInterval: 15m
  data:
    - secretKey: postgres_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_user
    - secretKey: postgres_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_pw
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-pgsql
  namespace: database
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        minio_s3_access_key: |-
          {{ .minio_user }}
        minio_s3_secret_access_key: |-
          {{ .minio_secret }}
  refreshInterval: 15m
  data:
    - secretKey: minio_user
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: adefec19-d343-4dc3-9028-b05d01565916
        property: username
    - secretKey: minio_secret
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: adefec19-d343-4dc3-9028-b05d01565916
        property: password
