---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/main/apps/monitoring/loki/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
