---
apiVersion: v1
kind: Service
metadata:
  name: dev-frontend
  namespace: dev-dentari
  labels:
    app: dev-frontend
  annotations:
    metallb.universe.tf/loadBalancerIP: "192.168.0.106"
spec:
  selector:
    app: dev-frontend
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8501
      targetPort: 8501
