---
apiVersion: v1
kind: Service
metadata:
  name: dev-backend
  namespace: dev-dentari
  labels:
    app: dev-backend
spec:
  selector:
    app: dev-backend
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
