apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dev-dentari-data-pvc
      namespace: dev-dentari
      labels:
        app: dev-dentari
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dev-dentari-cache-pvc
      namespace: dev-dentari
      labels:
        app: dev-dentari
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dev-dentari-logs-pvc
      namespace: dev-dentari
      labels:
        app: dev-dentari
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: dev-dentari-db-pvc
      namespace: dev-dentari
      labels:
        app: dev-dentari
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
