version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest@sha256:79053c07400eec909d04ac97db760c30bf61471ec37465a50f126a3c825a92bc
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /path/to/radarr/data:/config
      - /path/to/movies:/movies #optional
      - /path/to/download-client-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped