kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: sonarr
  namespace: sonarr
  annotations:
    kubernetes.io/ingress.class: traefik
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # traefik.ingress.kubernetes.io/router.middlewares: default-my-basic-auth@kubernetescrd
  labels:
    app: sonarr
spec:
  # tls:
  #   - secretName: "{{ appname }}"-home-local-tls
  #     hosts:
  #       - "{{ appdomain }}"
  rules:
  - host: sonarr.home.adaminformatika.hu
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sonarr
              port:
                number: 8989