---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      containers:
        - image: lscr.io/linuxserver/sonarr@sha256:9368864d37c43b088219c813c0de2b476f9ff2a36a388c67746370c3554b61d4
          name: sonarr
          ports:
            - containerPort: 8989
              name: sonarr-8989
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: sonarr-claim0
            - mountPath: /tv
              name: nfs-vol
            - mountPath: /downloads # The mountpoint inside the container
              name: nfs-vol
      restartPolicy: Always
      volumes:
        - name: sonarr-claim0
          persistentVolumeClaim:
            claimName: sonarr-claim0
        - name: nfs-vol
          nfs:
            server: 192.168.0.21 # IP to our NFS server
            path: /media/ # The path to our NFS share # The exported directory
