---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nas
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/default/nas/main"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nas-files
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/default/nas/files"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nas-photos
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/default/nas/photos"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
