---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-vaultwarden
  namespace: system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        VW_POSTGRES_HOST: &dbHost postgres-v16-rw.database.svc
        VW_POSTGRES_USER: &dbUser |-
          {{ .postgres_vw_user }}
        VW_POSTGRES_PASSWORD: &dbPass |-
          {{ .postgres_vw_pass }}
        DATABASE_URL: "postgresql://{{ .postgres_vw_user }}:{{ .postgres_vw_pass }}@postgres-v16-rw.database.svc.cluster.local/vaultwarden"
        # Postgres Init
        INIT_POSTGRES_DBNAME: vaultwarden
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .postgres_pw }}
  refreshInterval: 15m
  data:
    - secretKey: postgres_vw_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_vw_user
    - secretKey: postgres_vw_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_vw_pass
    - secretKey: postgres_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_pw
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ADMIN_TOKEN: |-
          {{ .vw_admin_token }}
        SMTP_USERNAME: |-
          {{ .smtp_user }}
        SMTP_PASSWORD: |-
          {{ .smtp_password }}
  refreshInterval: 15m
  data:
    - secretKey: vw_admin_token
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: vw_admin_token
    - secretKey: smtp_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: smtp_user
    - secretKey: smtp_password
      sourceRef:
        storeRef:
          name: bitwarden-notes
          kind: ClusterSecretStore
      remoteRef:
        key: a602848a-7af4-48e7-ab92-b0fc01440439
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: volsync-vaultwarden
  namespace: system
spec:
  target:
    deletionPolicy: Delete
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
        RESTIC_REPOSITORY: "s3:{{ .endpoint }}/volsync/vaultwarden"
        RESTIC_PASSWORD: "{{ .restic_password }}"
  refreshInterval: 15m
  data:
    - secretKey: access_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: username
    - secretKey: secret_key
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 81f62c51-4f2f-4938-ae4c-b11900eadd6d
        property: password
    - secretKey: endpoint
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: minio-s3-endpoint
    - secretKey: restic_password
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: restic_password
