apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bazarr-deploy.yaml
- bazarr-ing.yaml
- bazarr-pvc.yaml
- bazarr-svc.yaml
images:
- name: pmialon/bazarr
  newTag: 1.5.0
labels:
- includeSelectors: true
  pairs:
    app: bazarr
