---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: calibre-books
    labels:
      type: calibre-books
spec:
    accessModes:
    - ReadWriteOnce
    storageClassName: local-path
    resources:
      requests:
        storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: calibre-config
    labels:
      type: calibre-config
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-path
    resources:
      requests:
        storage: 200Mi
