apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- calibre-deploy.yaml
- calibre-ing.yaml
- calibre-pvc.yaml
- calibre-svc.yaml
images:
- name: linuxserver/calibre-web
  newTag: 7.18.0
labels:
- includeSelectors: true
  pairs:
    app: calibre
