image:
  repository: "ghcr.io/hotio/prowlarr"
  tag: "release-1.23.1.4708@sha256:81d902c27e0949f0a441b847b5838a6edbf340ca1739e9a0d9aa1f875da2caad"

ports: 
- name: main
  containerPort: 9696

ingress:
  host: prowlarr.wagner.gg

envs:
- PUID: 5000
- PGID: 5000

hostPaths:
- name: config
  hostPath: /srv/nvme/container-data/prowlarr
  containerPath: /config

homepage:
  name: Prowlarr
  group: Indexer
  description: Index Manager
  icon: prowlarr.svg
  weight: 10
