---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - image: lscr.io/linuxserver/overseerr@sha256:1642cffc2573e37d1972aa27e5e2bae9d91d320a326f232d58b8bfbba65832e7
          name: overseerr
          ports:
            - containerPort: 5055
              name: overseer
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: overseerr-claim0
      restartPolicy: Always
      volumes:
        - name: overseerr-claim0
          persistentVolumeClaim:
            claimName: overseerr-claim0
