---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - image: lscr.io/linuxserver/overseerr:latest
          name: overseerr
          ports:
            - containerPort: 5055
              name: overseer-5055
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: overseerr-claim0
      restartPolicy: Always
      volumes:
        - name: overseerr-claim0
          persistentVolumeClaim:
            claimName: overseerr-claim0
