---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-aggregator
  namespace: flux-system
spec:
  dependsOn:
    - name: loki
    - name: cluster-apps-external-secrets-stores
  path: ./kubernetes/main/apps/monitoring/vector/aggregator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vector-agent
  namespace: flux-system
spec:
  dependsOn:
    - name: vector-aggregator
  path: ./kubernetes/main/apps/monitoring/vector/agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
