apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sabnzbd-deploy.yaml
- sabnzbd-pvc.yaml
- sabnzbd-svc.yaml
- sabnzbd-ing.yaml
images:
- name: pmialon/sabnzbd
  newTag: 4.5.5
labels:
- includeSelectors: true
  pairs:
    app: sabnzbd
