---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
  labels:
    type: config
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ${SC_CONFIG:=local-path}
  resources:
    requests:
      storage: 500Mi
