---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: scrypted
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/main/apps/home/scrypted/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: cluster-apps-frigate
