---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo1
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemo1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flaskdemo1
    spec:
      containers:
      - name: flaskdemo1
        image: radam/flask-kubernetes@sha256:8ca83562c2ab77409d958c1f0ff965c9e6989d4d72c62a6e93f82d2dd2905d9e
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "384Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          protocol: TCP
          name: flaskdemo1
