---
apiVersion: v1
kind: Service
metadata:
  name: bedroompi
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: v1
kind: Endpoints
metadata:
  name: bedroompi
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.3
    ports:
      - port: 9000
        protocol: TCP
