---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fission-crds
  namespace: flux-system
spec:
  targetNamespace: serverless
  interval: 10m
  path: "./kubernetes/main/apps/serverless/fission/crd"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fission
  namespace: flux-system
spec:
  targetNamespace: serverless
  interval: 10m
  path: "./kubernetes/main/apps/serverless/fission/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: fission-crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fission-functions
  namespace: flux-system
spec:
  targetNamespace: serverless
  interval: 10m
  path: "./kubernetes/main/apps/serverless/fission/functions"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  dependsOn:
    - name: fission-crds
    - name: fission
