apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- speedtest-tracker-deploy.yaml
images:
- name: lscr.io/linuxserver/speedtest-tracker
  newTag: 1.3.0
labels:
- includeSelectors: true
  pairs:
    app: speedtest-tracker
