apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- speedtest-tracker-deploy.yaml
images:
- name: linuxserver/speedtest-tracker
  newTag: 1.6.6
labels:
- includeSelectors: true
  pairs:
    app: speedtest-tracker
