---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-backup
  namespace: default
spec:
  storageClassName: nfs-provision-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
