apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- flexget-deploy.yaml
- flexget-ing.yaml
- flexget-pvc.yaml
- flexget-svc.yaml
images:
- name: ghcr.io/flexget/flexget
  newTag: 3.13.23
labels:
- includeSelectors: true
  pairs:
    app: flexget
