apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- it-tools-deploy.yaml
images:
- name: corentinth/it-tools
  newTag: 2024.10.22-7ca5933
labels:
- includeSelectors: true
  pairs:
    app: it-tools
