---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flux-notifications
  namespace: flux-system
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        address: |-
          {{ .discord_url_flux_channel }}
  refreshInterval: 15m
  data:
    - secretKey: discord_url_flux_channel
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: discord_url_flux_channel
