---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 10m
  path: "./kubernetes/main/apps/monitoring/kube-prometheus-stack/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-cluster
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  dependsOn:
    - name: cluster-apps-external-secrets-stores
