---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: flux-system
type: Opaque
stringData:
  BW_CLIENTID: ENC[AES256_GCM,data:ktv+58si/A6Fu8Sf5/qNlE/+QuSnE77B+Mi29vhWwoO1vueRuJCLm6s=,iv:/tqN18t9rxzEhJcBghXPT6LnK8gkLpTilHz9iudI1Hc=,tag:nN7m4m1lBp7P1tAwKuf+vQ==,type:str]
  BW_CLIENTSECRET: ENC[AES256_GCM,data:nfzMRiCh2JFIMSSSlv7EwIPljXlqirheOD53DoOc,iv:mOBYYtoqUuZIJlWHkD5LHEbCBlsaTvDnp0xCqi8VcvM=,tag:H5PTsV+eV6YYj2FHnmB93Q==,type:str]
  BW_PASSWORD: ENC[AES256_GCM,data:J8xucCQXSXSv0BiWaHE=,iv:Ahi6XY1u8u6G1JT76ifoJU4Xyt8VwGLQ6go7FTrLExg=,tag:Gq5LF8pc/9UupOIpQ1DUgA==,type:str]
  BW_HOST: ENC[AES256_GCM,data:PaVTBx8frCfQOJCGBaTjEwYP/w==,iv:+la/cw93sn5dYW4mzS1N4wp/qu5ZGEudUZ3QuozTqr8=,tag:ifnB+wmYtAa4yX16+kb0qw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:eCLmnMxrvnY=,iv:X92s4mHuk+P7WPbTgXLANM/dOacNS6uXORaUNovIg4Y=,tag:C46FQAxu7T5vYYFZd04n1g==,type:str]
  VC_PASSWORD: ENC[AES256_GCM,data:qi7WEpJ0ouBDYY3Uj0Waax0HpZTuk/1W,iv:AnG97hNRv9VoXAHv7p8dycgGSl9v1qhM0tWr4n2KbhI=,tag:GUSYybwRWMpQY14UDP7IAg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age19mhznjzteas7egvnszjxr0msdd667sezwaz978562q4r30xsjvuqjfve3x
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa2JQL0kyVWNWNWdhZTdG
        TU1WZnlWV3pkcjkrMHRTMjBPa1J5MmlIaVdZCnVRM2U2cW5aOE5IL1RyMEptVEtn
        c1FLd0RLZmlxbVozVUtsdGQ3clk5VGcKLS0tIHJpNnY5RzdicVVlWi80V0J0N0ZQ
        WE4ySm5oRjFMTHRJdkRBZjduTzNNWlUKbWHEm6tt1Gc0JpTJNieO1ovC4hcJaVjJ
        UJ5HLmOJ1UtZ6fEmsjGSmsL4Qv8CwRv8F0+TXBUEDWAppWOlZyXIGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-11T23:01:20Z"
  mac: ENC[AES256_GCM,data:q5fZOGDbUy5xc3gFInUu32PrHAh1iNI5UtveGTu7CpdzGwXkcVPx3pLtPeFENvK2Ste8GJq73qWTcb9AyDPt3/tFDUW/mmlsPdKmDW21JLs6IF+6q0AN9E1MK4Yt0fVPr1dmdzP84q1csGIDI96gkpAmSUmePklssq+vkWvW+f0=,iv:pTn9XihlguYyI6SWTI7vGIX42Vxm+a8nzL8xTvU7Wzg=,tag:XhfDKXZ23h8kd/+Y1Oeqgg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
