services:
  app:
    build: 
      context: .
      args:
        codeartifact_token: ${CODEARTIFACT_AUTH_TOKEN}
    ports:
      - "8000:3000"
    env_file:
     - ./env/.env.example
    volumes:
      - ./logs:/var/app/log