apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- torrents-ingress.yaml
- qbittorrent-deploy.yaml
- qbittorrent-pvc.yaml
- qbittorrent-svc.yaml
images:
- name: lscr.io/linuxserver/qbittorrent
  newTag: 20.04.1
labels:
- includeSelectors: true
  pairs:
    app: qbittorrent
