---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-atuin
  namespace: default
spec:
  target:
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        ATUIN_DB_URI: |-
          postgres://{{ .postgres_atuin_user }}:{{ .postgres_atuin_pass }}@postgres-v16-rw.database.svc.cluster.local/atuin
        # Postgres Init
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: postgres-v16-rw.database.svc
        INIT_POSTGRES_USER: |-
          {{ .postgres_atuin_user }}
        INIT_POSTGRES_PASS: |-
          {{ .postgres_atuin_pass }}
        INIT_POSTGRES_SUPER_PASS: |-
          {{ .postgres_pw }}
  refreshInterval: 15m
  data:
    - secretKey: postgres_atuin_user
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_atuin_user
    - secretKey: postgres_atuin_pass
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_atuin_pass
    - secretKey: postgres_pw
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 336e4bd7-6293-48cc-8d5e-b05d01565916
        property: postgres_pw
