image:
  repository: "ghcr.io/hotio/radarr"
  tag: "release-5.10.4.9218@sha256:8589ea9fbeae68c97218e75924c9928c1598b734399cc33b39a664439d16d925"

podLabels:
  zfs-encryption: "true"

ports: 
- name: main
  containerPort: 7878

ingress:
  host: radarr.wagner.gg

envs:
- PUID: 5000
- PGID: 5000

hostPaths:
- name: config
  hostPath: /srv/nvme/container-data/radarr
  containerPath: /config
- name: downloads-torrent
  hostPath: /srv/downloads/Torrent
  containerPath: /downloads/torrent
- name: downloads-usenet
  hostPath: /srv/downloads/Usenet
  containerPath: /downloads/usenet
- name: movies
  hostPath: /srv/hdd/multimedia/Filme-Radarr
  containerPath: /movies
- name: live-music
  hostPath: /srv/hdd/multimedia/Live-Konzerte
  containerPath: /live-music

homepage:
  name: Radarr
  group: Indexer
  description: Movie Manager
  icon: radarr.svg
  weight: 12
